# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('_from', models.DateField()),
                ('to', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('exp_type', models.CharField(choices=[('education', 'Education'), ('work', 'Work')], max_length=10, verbose_name='Experience type')),
                ('skills', models.ManyToManyField(to='web_app.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('short_desc', models.CharField(max_length=140)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=b'', verbose_name='Imagen')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image center')),
                ('description', models.TextField()),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Demo URL')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('skills', models.ManyToManyField(to='web_app.Skill')),
            ],
        ),
    ]
