# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_experience_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
