# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20160720_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'Bio', 'verbose_name_plural': 'Bio'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name': 'Skill category', 'verbose_name_plural': 'Skill categories'},
        ),
    ]
