# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20160720_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Skill category', 'verbose_name_plural': 'Skill categories'},
        ),
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
