# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20160722_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='_from',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='to',
            new_name='date_to',
        ),
    ]
