# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
