# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20160728_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
