# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 21:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20160728_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
