# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_contactentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
